#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of sb_pipe.
#
# sb_pipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sb_pipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sb_pipe.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# $Revision: 1.0 $
# $Author: Piero Dalle Pezze $
# $Date: 2015-07-13 12:14:32 $



# Utilities for changing column names generated by copasi time course reports

import sys
import os, glob
import re



# Replaces a group of annotation strings from a generated copasi report file
# Input parameters
# report: The file (with path) of the report with extension
def replace_str_copasi_sim_report(report):

  # The with statement ensures that the file is closed correctly, 
  # and re-opening the file in "w" mode empties the file before you write to it. 
  # re.sub(pattern, replace, string) is the equivalent of s/pattern/replace/ in sed.
  with open(report, "r") as file:
    lines = file.readlines()
  with open(report, "w") as file:
    #for idx, line in lines:
    for i in range(len(lines)):
	if i < 1:
	  # First remove non-alphanumerics and non-underscores. 
	  # Then replaces whites with TAB.
	  # Finally use rstrip to remove the TAB at the end.
	  # [^\w] matches anything that is not alphanumeric or underscore
	  file.write(
	    re.sub(r"\s+", '\t', re.sub(r'[^\w]', " ", lines[i])).rstrip('\t') + '\n')
	else:
	  file.write(lines[i].rstrip('\t'))  

